In [3]:
import torch

# Creating Scalars

In [7]:
scalar = torch.tensor(7) # used to create a scalar
scalar

tensor(7)

In [9]:
scalar.ndim # used to check the dimensions

0

In [11]:
scalar.item() # to get the number within a tensor

7

# Creating Vectors

In [13]:
vector = torch.tensor([7,7]) #used to create a vector
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [19]:
#vector.item()
#This code is giving runtime error because item cannot convert any tensor that have more than one element. To do we have to use indexing method

In [23]:
vector[0].item()

7

In [27]:
vector.shape # this shape method is different from ndim. It tell us the number of dimensions inside a tensor while ndim tells the outer dimension

torch.Size([2])

# Creating Matrix

In [44]:
matrix = torch.tensor([[1,2,3],
              [5,6,7],
              [7,8,9]])
matrix

tensor([[1, 2, 3],
        [5, 6, 7],
        [7, 8, 9]])

In [46]:
matrix.shape

torch.Size([3, 3])

In [48]:
matrix.ndim

2

# Random Tensors

In [84]:
rand_tensors = torch.rand(size = (2,3,2,6))
rand_tensors.shape,rand_tensors.ndim

(torch.Size([2, 3, 2, 6]), 4)

# Zeros and ones Tensors

In [90]:
zeros = torch.zeros(size = (3,4))
zeros, zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 2)

In [94]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [96]:
range = torch.arange(0,10,2)
range

tensor([0, 2, 4, 6, 8])

In [102]:
#if you want to create a tensor of zeros or ones with the same shape, you can use
zero_like = torch.zeros_like(input = range)
zero_like

tensor([0, 0, 0, 0, 0])

# Tensor Datatypes

In [124]:
float32_tensor = torch.tensor(data = [1.0,3],
            dtype = None,
            device = None,
            requires_grad = False)
float32_tensor, float32_tensor.ndim, float32_tensor.shape, float32_tensor.device, float32_tensor.dtype

(tensor([1., 3.]), 1, torch.Size([2]), device(type='cpu'), torch.float32)

In [116]:
float32_tensor = torch.tensor(data = [1,2,3],
            dtype = torch.float16,
            device = None,
            requires_grad = False)
float32_tensor, float32_tensor.ndim, float32_tensor.shape, float32_tensor.device, float32_tensor.dtype

(tensor([1., 2., 3.], dtype=torch.float16),
 1,
 torch.Size([3]),
 device(type='cpu'),
 torch.float16)

# Manipulating Tensors - Basic operations

In [177]:
rand1 = torch.rand(size = (2,1,3,4))
rand1


tensor([[[[0.1183, 0.9437, 0.1024, 0.2358],
          [0.6343, 0.3198, 0.0477, 0.9365],
          [0.6179, 0.4088, 0.2416, 0.9439]]],


        [[[0.2786, 0.8043, 0.6950, 0.4803],
          [0.1325, 0.3460, 0.5688, 0.6646],
          [0.6604, 0.9921, 0.0427, 0.1175]]]])

In [179]:
rand1 + 10

tensor([[[[10.1183, 10.9437, 10.1024, 10.2358],
          [10.6343, 10.3198, 10.0477, 10.9365],
          [10.6179, 10.4088, 10.2416, 10.9439]]],


        [[[10.2786, 10.8043, 10.6950, 10.4803],
          [10.1325, 10.3460, 10.5688, 10.6646],
          [10.6604, 10.9921, 10.0427, 10.1175]]]])

In [181]:
rand1 - 10

tensor([[[[-9.8817, -9.0563, -9.8976, -9.7642],
          [-9.3657, -9.6802, -9.9523, -9.0635],
          [-9.3821, -9.5912, -9.7584, -9.0561]]],


        [[[-9.7214, -9.1957, -9.3050, -9.5197],
          [-9.8675, -9.6540, -9.4312, -9.3354],
          [-9.3396, -9.0079, -9.9573, -9.8825]]]])

In [185]:
rand1 * 20

tensor([[[[ 2.3656, 18.8748,  2.0485,  4.7152],
          [12.6864,  6.3962,  0.9533, 18.7300],
          [12.3586,  8.1764,  4.8320, 18.8777]]],


        [[[ 5.5715, 16.0865, 13.8999,  9.6070],
          [ 2.6509,  6.9198, 11.3764, 13.2914],
          [13.2087, 19.8423,  0.8534,  2.3493]]]])

In [189]:
torch.multiply(rand1, 10)

tensor([[[[1.1828, 9.4374, 1.0242, 2.3576],
          [6.3432, 3.1981, 0.4767, 9.3650],
          [6.1793, 4.0882, 2.4160, 9.4389]]],


        [[[2.7858, 8.0433, 6.9499, 4.8035],
          [1.3254, 3.4599, 5.6882, 6.6457],
          [6.6044, 9.9211, 0.4267, 1.1747]]]])

In [247]:
tensor1 = torch.randn(10,5,3,4)
tensor2 = torch.randn(10,5,4,6)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 5, 3, 6])

In [217]:
# There are some rules for the matrix multiplication. 
    #1. The inner dimensions must be same.
    #2. The outer dimensions will be the ouput tensor shape.
    #3. For the tensors having more than 2 dimensions, the batch sizes must match. For example, (10,2,4) , (10,4,5) : as the last dimension of tensor1 is 
        #4 and second-to-last dimension of second tensor is 4 so the output shape will be (2,5). Also, see that batch size is also same. 
    #4. If we have two tensors having same rows and column, but the batch size is missing in any one of the tensor, then it will add an additional dimension
        #in the missing tensor and remove the output. Example is given in the below cell.

In [251]:
tensor1 = torch.randn(10, 3, 4,5)
tensor2 = torch.randn(3,5, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 4, 5])

In [253]:
# There are different ways to multiply tensors
#tensor1*tensor2
#tensor1@tensor2
#torch.matmul(tensor1,tensor2)

In [11]:
%%time

import torch
tens1 = torch.tensor([4,5,8])
value = 0
for i in range(len(tens1)):
    value += tens1[i]*tens1[i]
value

CPU times: total: 0 ns
Wall time: 1 ms


tensor(105)

In [13]:
%%time
tens3 = torch.matmul(tens1,tens1)
tens3

#it is recommended to use matmul because of the time.

CPU times: total: 0 ns
Wall time: 0 ns


tensor(105)

In [30]:
#If we are getting a shape error, then we can simply transpose any matrix.
tens2 = torch.tensor([[1,2,3,3],
                     [1,2,3,4]])
tens4 = torch.transpose(input = tens2,dim0 = 0,dim1 = 1)
tens4

tensor([[1, 1],
        [2, 2],
        [3, 3],
        [3, 4]])

# Getting a GPU

In [33]:
!nvidia-smi

Tue Sep 24 14:37:34 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 532.03                 Driver Version: 532.03       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4060 Ti    WDDM | 00000000:01:00.0  On |                  N/A |
|  0%   35C    P8               11W / 160W|    652MiB /  8188MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [35]:
torch.cuda.is_available()

True

In [37]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [39]:
torch.cuda.device_count()

1

In [41]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [43]:
tensor.to(device)

tensor([1, 2, 3], device='cuda:0')

In [47]:
#to get back on cpu
tensor.cpu().numpy() , tensor.device

(array([1, 2, 3], dtype=int64), device(type='cpu'))